os:
  - linux
language: php

php:
  - '7.3'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 12.18.2
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install

script:
  - php artisan key:generate
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/assets/js/modules/*

notifications:
  - fernando@bitquark.com.mx